CREATE TABLE reviews (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36),
    agent_id VARCHAR(255),
    language VARCHAR(50) NOT NULL,
    source_type VARCHAR(30) NOT NULL DEFAULT 'code_paste',
    source_meta JSON,
    review_mode VARCHAR(20) NOT NULL DEFAULT 'full',
    executor_type VARCHAR(30) NOT NULL DEFAULT 'CLAUDE_API',
    executor_config JSON,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    task_description TEXT,
    risk_score INT,
    risk_label VARCHAR(20),
    recommendation VARCHAR(10),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    duration_ms BIGINT,
    INDEX idx_user_id (user_id),
    INDEX idx_agent_id (agent_id),
    INDEX idx_created_at (created_at),
    INDEX idx_recommendation (recommendation),
    INDEX idx_status (status)
);
